// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN8zjBQHLaHaSFWtKiMOVL2a7NgtVQZgw',
    appId: '1:1063564734011:web:b94a21aa614aadcbfff61e',
    messagingSenderId: '1063564734011',
    projectId: 'travel-app-41225',
    authDomain: 'travel-app-41225.firebaseapp.com',
    storageBucket: 'travel-app-41225.appspot.com',
    measurementId: 'G-GCN55198QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZXxh5kohPfVWEZRxlcxuSpaqJlkn5wQ',
    appId: '1:1063564734011:android:5d830e42a54df29cfff61e',
    messagingSenderId: '1063564734011',
    projectId: 'travel-app-41225',
    storageBucket: 'travel-app-41225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUWhUNtCR3dQkA7ejqnft1DFCBg0joUuE',
    appId: '1:1063564734011:ios:e88cbd4a998c7d22fff61e',
    messagingSenderId: '1063564734011',
    projectId: 'travel-app-41225',
    storageBucket: 'travel-app-41225.appspot.com',
    iosBundleId: 'ma.emsi.travelManagementMobile',
  );
}
